/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package design;
import javax.swing.JFrame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author My PC
 */
public class adminhome extends javax.swing.JFrame {
    public static int open=0;

    /**
     * Creates new form adminhome
     */
    public adminhome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1415, 785));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 260, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 100, 260, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 280, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 410, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel11.setText("jLabel5");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 110));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel12.setText("jLabel5");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 260, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel13.setText("jLabel5");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 260, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel14.setText("jLabel5");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 260, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel15.setText("jLabel5");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 260, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel16.setText("jLabel5");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 260, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel17.setText("jLabel5");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 260, 170));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel18.setText("jLabel5");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 260, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel19.setText("jLabel5");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 260, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel20.setText("jLabel5");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 260, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel21.setText("jLabel5");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 260, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel22.setText("jLabel5");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 260, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel23.setText("jLabel5");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 260, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel24.setText("jLabel5");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 260, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel25.setText("jLabel5");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 260, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel26.setText("jLabel5");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 260, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel27.setText("jLabel5");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, 260, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel28.setText("jLabel5");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, 260, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel29.setText("jLabel5");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 510, 260, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel30.setText("jLabel5");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 260, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel31.setText("jLabel5");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 260, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel32.setText("jLabel5");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 260, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel33.setText("jLabel5");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 260, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel34.setText("jLabel5");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 260, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel35.setText("jLabel5");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 260, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel36.setText("jLabel5");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 610, 260, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel37.setText("jLabel5");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, 260, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel38.setText("jLabel5");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 190, 260, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel39.setText("jLabel5");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 460, 260, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel40.setText("jLabel5");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 320, 260, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel41.setText("jLabel5");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 600, 260, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpeg"))); // NOI18N
        jLabel42.setText("jLabel5");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 260, -1));

        jMenu1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        jMenu1.setText("Add Questions");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu1.setIconTextGap(20);
        jMenu1.setMargin(new java.awt.Insets(100, 100, 100, 100));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update (3).png"))); // NOI18N
        jMenu2.setText("Update Questions");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/select-all.png"))); // NOI18N
        jMenu3.setText("All Questions");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete (1).png"))); // NOI18N
        jMenu4.setText("Delete Questions");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/results.png"))); // NOI18N
        jMenu5.setText("All Student Result");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power-off.png"))); // NOI18N
        jMenu6.setText("Logout");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        jMenu7.setText("clear");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);
        int a=JOptionPane.showConfirmDialog(jf,"Do you really want to logout","select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new loginAdmin().setVisible(true);
        }
        
        
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);
        int a=JOptionPane.showConfirmDialog(jf,"Do you really want to Exit","select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
        
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        if(open==0){
            new AddnewQuestion().setVisible(true);
            open=1;
        }
        else{
           JFrame jf=new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf,"One from is already open");
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
         if(open==0){
            new UpdateQuestion().setVisible(true);
            open=1;
        }
        else{
           JFrame jf=new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf,"One from is already open");
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
          if(open==0){
            new AllQuestion().setVisible(true);
            open=1;
        }
        else{
           JFrame jf=new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf,"One from is already open");
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
         if(open==0){
            new DeleteQuestion().setVisible(true);
            open=1;
        }
        else{
           JFrame jf=new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf,"One from is already open");
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        if(open==0){
            new result().setVisible(true);
            open=1;
        }
        else{
           JFrame jf=new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf,"One from is already open");
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
