/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package design;

import javax.swing.JOptionPane;

/**
 *
 * @author My PC
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(247, 91, 44));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Student");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, -1));

        jPanel3.setBackground(new java.awt.Color(247, 91, 44));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Admin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jPanel4.setBackground(new java.awt.Color(247, 91, 44));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Exit");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, -1));

        jLabel4.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 91, 44));
        jLabel4.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 480, -1));

        jLabel5.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 91, 44));
        jLabel5.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 480, -1));

        jLabel6.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 91, 44));
        jLabel6.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 480, -1));

        jLabel7.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(247, 91, 44));
        jLabel7.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 480, 20));

        jLabel8.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(247, 91, 44));
        jLabel8.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 660, 480, -1));

        jLabel9.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 91, 44));
        jLabel9.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 480, -1));

        jLabel10.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(247, 91, 44));
        jLabel10.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 480, -1));

        jLabel11.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(247, 91, 44));
        jLabel11.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 430, 60));

        jLabel12.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(247, 91, 44));
        jLabel12.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 480, -1));

        jLabel13.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(247, 91, 44));
        jLabel13.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 480, -1));

        jLabel14.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(247, 91, 44));
        jLabel14.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 480, -1));

        jLabel15.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(247, 91, 44));
        jLabel15.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 480, -1));

        jLabel16.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(247, 91, 44));
        jLabel16.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 480, -1));

        jLabel17.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(247, 91, 44));
        jLabel17.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 480, -1));

        jLabel18.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(247, 91, 44));
        jLabel18.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 480, -1));

        jLabel19.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(247, 91, 44));
        jLabel19.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 480, -1));

        jLabel20.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(247, 91, 44));
        jLabel20.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 480, -1));

        jLabel21.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(247, 91, 44));
        jLabel21.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 480, -1));

        jLabel22.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(247, 91, 44));
        jLabel22.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 710, 480, -1));

        jLabel23.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(247, 91, 44));
        jLabel23.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, 480, -1));

        jLabel24.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(247, 91, 44));
        jLabel24.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 480, -1));

        jLabel25.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(247, 91, 44));
        jLabel25.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, 480, -1));

        jLabel26.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(247, 91, 44));
        jLabel26.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 550, 480, -1));

        jLabel27.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(247, 91, 44));
        jLabel27.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 480, -1));

        jLabel28.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(247, 91, 44));
        jLabel28.setText("sMaRt  qUiZ aPp");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, 480, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to Exit Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new loginAdmin().setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         setVisible(false);
        new studentlogin().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
